version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/web/
    file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 30
      runas: root
