version: 0.0
os: linux

file_exists_behavior: OVERWRITE

files:
  - source: /
    destination: /var/www/web-app/
    
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: root
